### ISSUE TITLE
5.3-apache: You don't have permission to access

### ISSUE THREAD

**Issue by MohammadMQ** [pretzlaw/docker-php#3]
When running the image 5.3-apache and then trying to access: http://127.0.0.1:8000/ I get following error

_Forbidden
You don't have permission to access / on this server._

**Comment by pretzlaw** [comment]
Hello there. This is normal until there is an "index.html", "index.php" or some other file provided.
See this `docker-compose.yml` for example:

```yaml
version: "3"

services:
  php:
    image: pretzlaw/php:5.3-apache
    ports:
    - "8000:80"
    volumes:
    - ".:/var/www/html"
```

Put an index.html in the same directory where the "docker-compose.yml" is.
After running `docker-compose up -d` it will show up in the browser:

![image](https://user-images.githubusercontent.com/24290366/72305995-e805f700-3675-11ea-9b87-2a69263fd7eb.png)

Does this solve the problem?
